version: "3"

services:
  web-test:
    container_name: web-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - ./:/app
